services:
  mongodb:
    image: 'mongo:6.0'
    environment:
      - 'MONGO_INITDB_DATABASE=tic-tac-med'
      - 'MONGO_INITDB_ROOT_PASSWORD=secret'
      - 'MONGO_INITDB_ROOT_USERNAME=root'
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data:
