package com.abba.tictacmed.application.dto;

public enum MessageReceivedType {

    WELCOME, REMINDER_CREATION, REMINDER_RESPONSE_TAKEN,
    REMINDER_RESPONSE_SKIPPED,
    REMINDER_CANCEL, PLAN_UPGRADE,
    PLAN_DOWNGRADE, SUPPORT, CHECK_NEXT_DISPATCH

}
